version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.10"

python:
  install:
    - requirements: doc/src/requirements.txt
    - method: pip
      path: .

sphinx:
  configuration: doc/src/conf.py
